"""add brand and features to products

Revision ID: 6d0e3a391ae7
Revises: 
Create Date: 2026-07-13 16:32:35.873251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0e3a391ae7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('features')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
