"""add customer name and email to gift card submissions

Revision ID: b53f985c01b5
Revises: 6d0e3a391ae7
Create Date: 2026-07-13 17:18:12.928554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53f985c01b5'
down_revision = '6d0e3a391ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_card_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_card_submissions', schema=None) as batch_op:
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
